/* Generated by Yosys 0.47+121 (git sha1 98b4affc4, g++ 13.2.0-23ubuntu4 -fPIC -O3) */

module dff_async_set(clk, async_set, d, q);
  wire _0_;
  wire _1_;
  wire _2_;
  input async_set;
  wire async_set;
  input clk;
  wire clk;
  input d;
  wire d;
  output q;
  wire q;
  sky130_fd_sc_hd__clkinv_1 _3_ (
    .A(_0_),
    .Y(_1_)
  );
  sky130_fd_sc_hd__dfstp_2 _4_ (
    .CLK(clk),
    .D(d),
    .Q(q),
    .SET_B(_2_)
  );
  assign _0_ = async_set;
  assign _2_ = _1_;
endmodule
