/* Generated by Yosys 0.47+121 (git sha1 98b4affc4, g++ 13.2.0-23ubuntu4 -fPIC -O3) */

module mux_generate(i0, i1, i2, i3, sel, y);
  wire _0_;
  input i0;
  wire i0;
  input i1;
  wire i1;
  input i2;
  wire i2;
  input i3;
  wire i3;
  input [1:0] sel;
  wire [1:0] sel;
  output y;
  reg y;
  sky130_fd_sc_hd__mux4_2 _1_ (
    .A0(i0),
    .A1(i1),
    .A2(i2),
    .A3(i3),
    .S0(sel[0]),
    .S1(sel[1]),
    .X(_0_)
  );
  always @*
    if (!1'h0) y = _0_;
endmodule
