/* Generated by Yosys 0.47+121 (git sha1 98b4affc4, g++ 13.2.0-23ubuntu4 -fPIC -O3) */

module rca(num1, num2, sum);
  wire \genblk1[1].u_fa_1.c ;
  wire \genblk1[1].u_fa_1.co ;
  wire \genblk1[1].u_fa_1.sum ;
  wire \genblk1[2].u_fa_1.co ;
  wire \genblk1[2].u_fa_1.sum ;
  wire \genblk1[3].u_fa_1.co ;
  wire \genblk1[3].u_fa_1.sum ;
  wire \genblk1[4].u_fa_1.co ;
  wire \genblk1[4].u_fa_1.sum ;
  wire \genblk1[5].u_fa_1.co ;
  wire \genblk1[5].u_fa_1.sum ;
  wire \genblk1[6].u_fa_1.co ;
  wire \genblk1[6].u_fa_1.sum ;
  wire \genblk1[7].u_fa_1.co ;
  wire \genblk1[7].u_fa_1.sum ;
  input [7:0] num1;
  wire [7:0] num1;
  input [7:0] num2;
  wire [7:0] num2;
  output [8:0] sum;
  wire [8:0] sum;
  wire \u_fa_0.sum ;
  sky130_fd_sc_hd__maj3_1 _00_ (
    .A(\genblk1[1].u_fa_1.c ),
    .B(num1[1]),
    .C(num2[1]),
    .X(\genblk1[1].u_fa_1.co )
  );
  sky130_fd_sc_hd__xor3_1 _01_ (
    .A(\genblk1[1].u_fa_1.c ),
    .B(num1[1]),
    .C(num2[1]),
    .X(\genblk1[1].u_fa_1.sum )
  );
  sky130_fd_sc_hd__maj3_1 _02_ (
    .A(\genblk1[1].u_fa_1.co ),
    .B(num1[2]),
    .C(num2[2]),
    .X(\genblk1[2].u_fa_1.co )
  );
  sky130_fd_sc_hd__xor3_1 _03_ (
    .A(\genblk1[1].u_fa_1.co ),
    .B(num1[2]),
    .C(num2[2]),
    .X(\genblk1[2].u_fa_1.sum )
  );
  sky130_fd_sc_hd__maj3_1 _04_ (
    .A(\genblk1[2].u_fa_1.co ),
    .B(num1[3]),
    .C(num2[3]),
    .X(\genblk1[3].u_fa_1.co )
  );
  sky130_fd_sc_hd__xor3_1 _05_ (
    .A(\genblk1[2].u_fa_1.co ),
    .B(num1[3]),
    .C(num2[3]),
    .X(\genblk1[3].u_fa_1.sum )
  );
  sky130_fd_sc_hd__maj3_1 _06_ (
    .A(\genblk1[3].u_fa_1.co ),
    .B(num1[4]),
    .C(num2[4]),
    .X(\genblk1[4].u_fa_1.co )
  );
  sky130_fd_sc_hd__xor3_1 _07_ (
    .A(\genblk1[3].u_fa_1.co ),
    .B(num1[4]),
    .C(num2[4]),
    .X(\genblk1[4].u_fa_1.sum )
  );
  sky130_fd_sc_hd__maj3_1 _08_ (
    .A(\genblk1[4].u_fa_1.co ),
    .B(num1[5]),
    .C(num2[5]),
    .X(\genblk1[5].u_fa_1.co )
  );
  sky130_fd_sc_hd__xor3_1 _09_ (
    .A(\genblk1[4].u_fa_1.co ),
    .B(num1[5]),
    .C(num2[5]),
    .X(\genblk1[5].u_fa_1.sum )
  );
  sky130_fd_sc_hd__maj3_1 _10_ (
    .A(\genblk1[5].u_fa_1.co ),
    .B(num1[6]),
    .C(num2[6]),
    .X(\genblk1[6].u_fa_1.co )
  );
  sky130_fd_sc_hd__xor3_1 _11_ (
    .A(\genblk1[5].u_fa_1.co ),
    .B(num1[6]),
    .C(num2[6]),
    .X(\genblk1[6].u_fa_1.sum )
  );
  sky130_fd_sc_hd__maj3_1 _12_ (
    .A(\genblk1[6].u_fa_1.co ),
    .B(num1[7]),
    .C(num2[7]),
    .X(\genblk1[7].u_fa_1.co )
  );
  sky130_fd_sc_hd__xor3_1 _13_ (
    .A(\genblk1[6].u_fa_1.co ),
    .B(num1[7]),
    .C(num2[7]),
    .X(\genblk1[7].u_fa_1.sum )
  );
  sky130_fd_sc_hd__maj3_1 _14_ (
    .A(1'h0),
    .B(num1[0]),
    .C(num2[0]),
    .X(\genblk1[1].u_fa_1.c )
  );
  sky130_fd_sc_hd__xor3_1 _15_ (
    .A(1'h0),
    .B(num1[0]),
    .C(num2[0]),
    .X(\u_fa_0.sum )
  );
  assign sum = { \genblk1[7].u_fa_1.co , \genblk1[7].u_fa_1.sum , \genblk1[6].u_fa_1.sum , \genblk1[5].u_fa_1.sum , \genblk1[4].u_fa_1.sum , \genblk1[3].u_fa_1.sum , \genblk1[2].u_fa_1.sum , \genblk1[1].u_fa_1.sum , \u_fa_0.sum  };
endmodule
