/* Generated by Yosys 0.47+121 (git sha1 98b4affc4, g++ 13.2.0-23ubuntu4 -fPIC -O3) */

module dff_asyncres_syncres(clk, async_reset, sync_reset, d, q);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  input async_reset;
  wire async_reset;
  input clk;
  wire clk;
  input d;
  wire d;
  output q;
  reg q;
  input sync_reset;
  wire sync_reset;
  sky130_fd_sc_hd__nor2b_1 _4_ (
    .A(_3_),
    .B_N(_2_),
    .Y(_1_)
  );
  always @(posedge clk, posedge async_reset)
    if (async_reset) q <= 1'h0;
    else q <= _0_;
  assign _2_ = d;
  assign _3_ = sync_reset;
  assign _0_ = _1_;
endmodule
