/* Generated by Yosys 0.47+121 (git sha1 98b4affc4, g++ 13.2.0-23ubuntu4 -fPIC -O3) */

module multiple_module_opt(a, b, c, d, y);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  wire _4_;
  input a;
  wire a;
  input b;
  wire b;
  input c;
  wire c;
  input d;
  wire d;
  output y;
  wire y;
  sky130_fd_sc_hd__a21o_1 _5_ (
    .A1(_1_),
    .A2(_2_),
    .B1(_3_),
    .X(_4_)
  );
  assign _1_ = a;
  assign _2_ = b;
  assign _3_ = c;
  assign y = _4_;
endmodule
