/* Generated by Yosys 0.47+121 (git sha1 98b4affc4, g++ 13.2.0-23ubuntu4 -fPIC -O3) */

module incomp_if(i0, i1, i2, y);
  input i0;
  wire i0;
  input i1;
  wire i1;
  input i2;
  wire i2;
  output y;
  reg y;
  always @*
    if (i0) y = i1;
endmodule
