/* Generated by Yosys 0.47+121 (git sha1 98b4affc4, g++ 13.2.0-23ubuntu4 -fPIC -O3) */

module dff_syncres(clk, async_reset, sync_reset, d, q);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  input async_reset;
  wire async_reset;
  input clk;
  wire clk;
  input d;
  wire d;
  output q;
  wire q;
  input sync_reset;
  wire sync_reset;
  sky130_fd_sc_hd__nor2b_1 _4_ (
    .A(_2_),
    .B_N(_1_),
    .Y(_0_)
  );
  sky130_fd_sc_hd__dfxtp_1 _5_ (
    .CLK(clk),
    .D(_3_),
    .Q(q)
  );
  assign _1_ = d;
  assign _2_ = sync_reset;
  assign _3_ = _0_;
endmodule
